AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Builds:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lks-sample-builds
  Gateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: lks-gateway
      ProtocolType: HTTP
  GatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: default
      AutoDeploy: true
      ApiId: !Ref Gateway
    