AWSTemplateFormatVersion: 2010-09-09
Resources:
  FunctionIAM:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: lks-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:PutObject'
                Resource: '*'
  Gateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: lks-gateway
      ProtocolType: HTTP
  GatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: default
      AutoDeploy: true
      ApiId: !Ref Gateway
  FGetData:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: lksgetdata
      Handler: lkslambda
      Runtime: go1.x
      Timeout: 30
      MemorySize: 128
      Role: !GetAtt FunctionIAM.Arn
      Code:
        S3Bucket: lks-builds
        S3Key: lkslambda-0.0.1.zip
  FGetDataPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - FGetData
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: lksgetdata
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ['',['arn:aws:execute-api:',!Ref AWS::Region,':',!Ref AWS::AccountId,':',!Ref Gateway,'/*/*/','lksgetdata']]
  FGetDataApi:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref Gateway
      IntegrationType: AWS_PROXY
      IntegrationMethod: ANY
      IntegrationUri: !Join ['',['arn:aws:apigateway:',!Ref 'AWS::Region',':lambda:path/2015-03-31/functions/',!GetAtt FGetData.Arn,'/invocations']]
      ConnectionType: INTERNET
      PayloadFormatVersion: '1.0'
  FGetDataRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref Gateway
      RouteKey: !Join ['',['ANY /','lksgetdata']]
      AuthorizationType: NONE
      Target: !Join ['',['integrations/',!Ref FGetDataApi]]
  
  
    