name: Build
on:
  push:
    branches:
      - main
env:
  appname: sample-game
  aws-region: 'us-east-1'
jobs:
  awscloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          lfs: 'false'
      
      - uses: paulhatch/semantic-version@v3.2
        id: semantic
        with:
          branch: "main"
          tag_prefix: ""
          bump_each_commit: false
      
      #- name: Run Shell Script
        #run: |
          #echo "version = ${{ steps.semantic.outputs.version }}"
          #echo "appname = ${{ env.appname }}-${{ steps.semantic.outputs.version }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}
        
      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: lks-development-stack
          template: Assets/Server/Cloud/cloud.yaml
          #parameter-overrides: 'BackendName=${{ env.BACKEND_NAME }}'
          no-fail-on-empty-changeset: "1"
      
      - uses: shallwefootball/s3-upload-action@master
        name: Upload Templates to S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: lks-sample-builds
          source_dir: 'Assets/Server/Cloud/Templates'
          destination_dir: ''
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
          stable: true
      
      - name: Build Lambda and Cook
        run: |
          mkdir Staging
          cd Assets/Server/Lambda/
          go get -d ./...
          GOOS=linux
          GOARCH=amd64
          go build -o lkslambda .
          zip ../../../Staging/lkslambda-${{ steps.semantic.outputs.version }}.zip lkslambda

      - uses: shallwefootball/s3-upload-action@master
        name: Upload Lambda to S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: lks-sample-builds
          source_dir: 'Staging'
          destination_dir: ''

      